# Lab 2: ML Life Cycle: Data Understanding and Data Preparation

In [1]:
import os
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt 
import seaborn as sns

In this lab, you will practice the second and third steps of the machine learning life cycle: data understanding and data preparation. You will beging preparing your data so that it can be used to train a machine learning model that solves a regression problem. Note that by the end of the lab, your data set won't be completely ready for the modeling phase, but you will gain experience using some common data preparation techniques. 

You will complete the following tasks to transform your data:

1. Build your data matrix and define your ML problem:
    * Load the Airbnb "listings" data set into a DataFrame and inspect the data
    * Define the label and convert the label's data type to one that is more suitable for modeling
    * Identify features
2. Clean your data:
    * Handle outliers by building a new regression label column by winsorizing outliers
    * Handle missing data by replacing all missing values in the dataset with means
3. Perform feature transformation using one-hot encoding
4. Explore your data:
    * Identify two features with the highest correlation with label
    * Build appropriate bivariate plots to visualize the correlations between features and the label
5. Analysis:
    * Analyze the relationship between the features and the label
    * Brainstorm what else needs to be done to fully prepare the data for modeling

## Part 1. Build Your Data Matrix (DataFrame) and Define Your ML Problem

#### Load a Data Set and Save it as a Pandas DataFrame

We will be working with the Airbnb NYC "listings" data set. Use the specified path and name of the file to load the data. Save it as a Pandas DataFrame called `df`.

In [2]:
# Do not remove or edit the line below:
filename = os.path.join(os.getcwd(), "data", "airbnbData.csv")

**Task**: Load the data and save it to DataFrame `df`.

<i>Note:</i> You may receive a warning message. Ignore this warning.

In [3]:
# YOUR CODE HERE
df = pd.read_csv(filename)

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (67) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

####  Inspect the Data

<b>Task</b>: Display the shape of `df` -- that is, the number of rows and columns.

In [4]:
# YOUR CODE HERE
df.shape

(38277, 74)

<b>Task</b>: Display the column names.

In [5]:
# YOUR CODE HERE
list(df.columns)

['id',
 'listing_url',
 'scrape_id',
 'last_scraped',
 'name',
 'description',
 'neighborhood_overview',
 'picture_url',
 'host_id',
 'host_url',
 'host_name',
 'host_since',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'latitude',
 'longitude',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bathrooms_text',
 'bedrooms',
 'beds',
 'amenities',
 'price',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'calendar_updated',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'calendar_last_scraped',
 'number_of_reviews',
 'number_of_reviews_ltm',
 'number_of_reviews_l30d',
 'first_review',
 'last_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'license',
 'instant_bookable',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'reviews_per_month']

**Task**: Get a peek at the data by displaying the first few rows, as you usually do.

In [6]:
# YOUR CODE HERE
df.head()

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2595,https://www.airbnb.com/rooms/2595,20211204143024,2021-12-05,Skylit Midtown Castle,"Beautiful, spacious skylit studio in the heart...",Centrally located in the heart of Manhattan ju...,https://a0.muscache.com/pictures/f0813a11-40b2...,2845,https://www.airbnb.com/users/show/2845,...,4.79,4.86,4.41,NaN,f,3,3,0,0,0.33
1,3831,https://www.airbnb.com/rooms/3831,20211204143024,2021-12-05,"Whole flr w/private bdrm, bath & kitchen(pls r...","Enjoy 500 s.f. top floor in 1899 brownstone, w...",Just the right mix of urban center and local n...,https://a0.muscache.com/pictures/e49999c2-9fd5...,4869,https://www.airbnb.com/users/show/4869,...,4.80,4.71,4.64,NaN,f,1,1,0,0,4.86
2,5121,https://www.airbnb.com/rooms/5121,20211204143024,2021-12-05,BlissArtsSpace!,<b>The space</b><br />HELLO EVERYONE AND THANK...,NaN,https://a0.muscache.com/pictures/2090980c-b68e...,7356,https://www.airbnb.com/users/show/7356,...,4.91,4.47,4.52,NaN,f,2,0,2,0,0.52
3,5136,https://www.airbnb.com/rooms/5136,20211204143024,2021-12-05,"Spacious Brooklyn Duplex, Patio + Garden",We welcome you to stay in our lovely 2 br dupl...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,7378,https://www.airbnb.com/users/show/7378,...,5.00,4.50,5.00,NaN,f,1,1,0,0,0.02
4,5178,https://www.airbnb.com/rooms/5178,20211204143024,2021-12-05,Large Furnished Room Near B'way,Please don’t expect the luxury here just a bas...,"Theater district, many restaurants around here.",https://a0.muscache.com/pictures/12065/f070997...,8967,https://www.airbnb.com/users/show/8967,...,4.42,4.87,4.36,NaN,f,1,0,1,0,3.68

#### Define the Label

Assume that your goal is to train a machine learning model that predicts the price of an Airbnb. This is an example of supervised learning and is a regression problem. In our dataset, our label will be the `price` column. Let's inspect the values in the `price` column.

In [7]:
df['price']

0        $150.00
1         $75.00
2         $60.00
3        $275.00
4         $68.00
          ...
38272     $79.00
38273     $76.00
38274    $116.00
38275    $106.00
38276    $689.00
Name: price, Length: 38277, dtype: object

Notice the `price` column contains values that are listed as $<$currency_name$>$$<$numeric_value$>$. 
<br>For example, it contains values that look like this: `$120`. <br>

**Task**:  Obtain the data type of the values in this column:

In [8]:
# YOUR CODE HERE
df.dtypes
# type(df['price'])
df['price'].dtypes

dtype('O')

Notice that the data type is "object," which in Pandas translates to the String data type.

**Task**:  Display the first 15 unique values of  the `price` column:

In [9]:
# YOUR CODE HERE
df['price'].unique()[:15]

array(['$150.00', '$75.00', '$60.00', '$275.00', '$68.00', '$98.00',
       '$89.00', '$65.00', '$62.00', '$90.00', '$199.00', '$96.00',
       '$299.00', '$140.00', '$175.00'], dtype=object)

In order for us to use the prices for modeling, we will have to transform the values in the `price` column from strings to floats. We will:

* remove the dollar signs (in this case, the platform forces the currency to be the USD, so we do not need to worry about targeting, say, the Japanese Yen sign, nor about converting the values into USD). 
* remove the commas from all values that are in the thousands or above: for example, `$2,500`. 

The code cell below accomplishes this.

In [10]:
df['price'] = df['price'].str.replace(',', '')
df['price'] = df['price'].str.replace('$', '')
df['price'] = df['price'].astype(float)

**Task**:  Display the first 15 unique values of  the `price` column again to make sure they have been transformed.

In [11]:
# YOUR CODE HERE
df['price'].unique()[:15]

array([150.,  75.,  60., 275.,  68.,  98.,  89.,  65.,  62.,  90., 199.,
        96., 299., 140., 175.])

#### Identify Features

Simply by inspecting the data, let's identify some columns that should not serve as features - those that will not help us solve our predictive ML problem.

Some that stand out are columns that contain website addresses (URLs).

**Task**: Create a list which contains the names of columns that contain URLs. Save the resulting list to variable `url_colnames`.

*Tip*: There are different ways to accomplish this, including using Python list comprehensions.

In [12]:
# YOUR CODE HERE
url_colnames = []
for label in df.columns:
    if '_url' in label:
        url_colnames.append(label)

url_colnames

['listing_url',
 'picture_url',
 'host_url',
 'host_thumbnail_url',
 'host_picture_url']

**Task**: Drop the columns with the specified names contained in list `url_colnames` in place (that is, make sure this change applies to the original DataFrame `df`, instead of creating a temporary new DataFrame object with fewer columns).

In [13]:
# YOUR CODE HERE
newdf = df.drop(url_colnames,axis=1,inplace=True)
newdf

**Task**: Display the shape of the data to verify that the new number of columns is what you expected.

In [14]:
# YOUR CODE HERE
df.shape

(38277, 69)

**Task**: In the code cell below, display the features that we will use to solve our ML problem.

In [15]:
# YOUR CODE HERE
# df.head(2)
# df.describe()
# df.info()
list(df.columns)

['id',
 'scrape_id',
 'last_scraped',
 'name',
 'description',
 'neighborhood_overview',
 'host_id',
 'host_name',
 'host_since',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'latitude',
 'longitude',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bathrooms_text',
 'bedrooms',
 'beds',
 'amenities',
 'price',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'calendar_updated',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'calendar_last_scraped',
 'number_of_reviews',
 'number_of_reviews_ltm',
 'number_of_reviews_l30d',
 'first_review',
 'last_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'license',
 'instant_bookable',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'reviews_per_month']

**Task**: Are there any other features that you think may not be well suited for our machine learning problem? Note your findings in the markdown cell below.

<Double click this Markdown cell to make it editable, and record your findings here.>

I dropped the id column because it is not relevant. The scrape_id, host_id, host_has_profile_pic, latitude, longitude, host_about were also columns that do not affect the predictive label outcome.

## Part 2. Clean Your Data

Let's now handle outliers and missing data.

### a. Handle Outliers

Let us prepare the data in our label column. Namely, we will detect and replace outliers in the data using winsorization.

**Task**: Create a new version of the `price` column, named `label_price`, in which you will replace the top and bottom 1% outlier values with the corresponding percentile value. Add this new column to the DataFrame `df`.

Remember, you will first need to load the `stats` module from the `scipy` package:

In [16]:
# YOUR CODE HERE 
from scipy import stats

df['label_price'] = stats.mstats.winsorize(df['price'], limits=[0.01, 0.01])

for x in df.columns:
    if 'label_price' in x:
        print(True)
        # checking if the new column was added to the dataframe

True

Let's verify that the new column `label_price` was added to DataFrame `df`:

In [17]:
df.head(0)

Empty DataFrame
Columns: [id, scrape_id, last_scraped, name, description, neighborhood_overview, host_id, host_name, host_since, host_location, host_about, host_response_time, host_response_rate, host_acceptance_rate, host_is_superhost, host_neighbourhood, host_listings_count, host_total_listings_count, host_verifications, host_has_profile_pic, host_identity_verified, neighbourhood, neighbourhood_cleansed, neighbourhood_group_cleansed, latitude, longitude, property_type, room_type, accommodates, bathrooms, bathrooms_text, bedrooms, beds, amenities, price, minimum_nights, maximum_nights, minimum_minimum_nights, maximum_minimum_nights, minimum_maximum_nights, maximum_maximum_nights, minimum_nights_avg_ntm, maximum_nights_avg_ntm, calendar_updated, has_availability, availability_30, availability_60, availability_90, availability_365, calendar_last_scraped, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, first_review, last_review, review_scores_rating, review_scores_accuracy, review_scores_cleanliness, review_scores_checkin, review_scores_communication, review_scores_location, review_scores_value, license, instant_bookable, calculated_host_listings_count, calculated_host_listings_count_entire_homes, calculated_host_listings_count_private_rooms, calculated_host_listings_count_shared_rooms, reviews_per_month, label_price]
Index: []

[0 rows x 70 columns]

**Task**: Check that the values of `price` and `label_price` are *not* identical. 

You will do this by subtracting the two columns and finding the resulting *unique values*  of the resulting difference. <br>Note: If all values are identical, the difference would not contain unique values. If this is the case, outlier removal did not work.

In [18]:
# YOUR CODE HERE
sub = df['price'] - df['label_price']
sub

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
38272    0.0
38273    0.0
38274    0.0
38275    0.0
38276    0.0
Length: 38277, dtype: float64

### b. Handle Missing Data

Next we are going to find missing values in our entire dataset and impute the missing values by
replace them with means.

#### Identifying missingness

**Task**: Check if a given value in the data is missing, and sum up the resulting values by columns. Save this sum to variable `nan_count`. Print the results.

In [19]:
nan_count = np.sum(df.isnull(), axis=0)
# nan_count = np.sum(df.isnull(), axis = 0)
nan_count

id                                                 0
scrape_id                                          0
last_scraped                                       0
name                                              13
description                                     1192
                                                ...
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               9504
label_price                                        0
Length: 70, dtype: int64

Those are more columns than we can eyeball! For this exercise, we don't care about the number of missing values -- we just want to get a list of columns that have *any* missing values.

<b>Task</b>: From the variable `nan_count`, create a new series called `nan_detected` that contains `True` or `False` values that indicate whether the number of missing values is *not zero*:

In [21]:
nan_detected = nan_count != 0
nan_detected

id                                              False
scrape_id                                       False
last_scraped                                    False
name                                             True
description                                      True
                                                ...
calculated_host_listings_count_entire_homes     False
calculated_host_listings_count_private_rooms    False
calculated_host_listings_count_shared_rooms     False
reviews_per_month                                True
label_price                                     False
Length: 70, dtype: bool

Since replacing the missing values with the mean only makes sense for the columns that contain numerical values (and not for strings), let us create another condition: the *type* of the column must be `int` or `float`.

**Task**: Create a series that contains `True` if the type of the column is either `int64` or `float64`. Save the results to the variable `is_int_or_float`.

In [41]:
is_int_or_float = df.dtypes.apply(lambda x: x in ['int64','float64'])
is_int_or_float

id                                               True
scrape_id                                        True
last_scraped                                    False
name                                            False
description                                     False
                                                ...
calculated_host_listings_count_entire_homes      True
calculated_host_listings_count_private_rooms     True
calculated_host_listings_count_shared_rooms      True
reviews_per_month                                True
label_price                                      True
Length: 70, dtype: bool

<b>Task</b>: Combine the two binary series (`nan_detected` and `is_int_or_float`) into a new series named `to_impute`. It will contain the value `True` if a column contains missing values *and* is of type 'int' or 'float'

In [46]:
nan_detected = df.isnull().any()
# create a series nan_detected

is_int_or_float = df.dtypes.apply(lambda x: x in ['int64','float64'])

to_impute = nan_detected & is_int_or_float

to_impute

id                                              False
scrape_id                                       False
last_scraped                                    False
name                                            False
description                                     False
                                                ...
calculated_host_listings_count_entire_homes     False
calculated_host_listings_count_private_rooms    False
calculated_host_listings_count_shared_rooms     False
reviews_per_month                                True
label_price                                     False
Length: 70, dtype: bool

Finally, let's display a list that contains just the selected column names contained in `to_impute`:

In [47]:
df.columns[to_impute]

Index(['host_listings_count', 'host_total_listings_count', 'bathrooms',
       'bedrooms', 'beds', 'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'reviews_per_month'],
      dtype='object')

We just identified and displayed the list of candidate columns for potentially replacing missing values with the column mean.

Assume that you have decided that you should impute the values for these specific columns: `host_listings_count`, `host_total_listings_count`, `bathrooms`, `bedrooms`, and `beds`:

In [48]:
to_impute_selected = ['host_listings_count', 'host_total_listings_count', 'bathrooms',
       'bedrooms', 'beds']

#### Keeping record of the missingness: creating dummy variables

As a first step, you will now create dummy variables indicating the missingness of the values.

**Task**: For every column listed in `to_impute_selected`, create a new corresponding column called `<original-column-name>_na`. These columns should contain the a `True`or `False` value in place of `NaN`.

In [52]:
# YOUR CODE HERE 
for x in to_impute[to_impute].index:
    df[f"{x}_na"] = df[x].isnull()
    print(df[f"{x}_na"])

0        False
1        False
2        False
3        False
4        False
         ...
38272    False
38273    False
38274    False
38275    False
38276    False
Name: host_listings_count_na, Length: 38277, dtype: bool
0        False
1        False
2        False
3        False
4        False
         ...
38272    False
38273    False
38274    False
38275    False
38276    False
Name: host_total_listings_count_na, Length: 38277, dtype: bool
0        True
1        True
2        True
3        True
4        True
         ...
38272    True
38273    True
38274    True
38275    True
38276    True
Name: bathrooms_na, Length: 38277, dtype: bool
0         True
1        False
2        False
3        False
4        False
         ...
38272    False
38273    False
38274    False
38275    False
38276    False
Name: bedrooms_na, Length: 38277, dtype: bool
0        False
1        False
2        False
3        False
4        False
         ...
38272     True
38273     True
38274    False
38275    False
38276    False
Name: beds_na, Length: 38277, dtype: bool
0        False
1        False
2        False
3        False
4        False
         ...
38272    False
38273    False
38274    False
38275    False
38276    False
Name: minimum_minimum_nights_na, Length: 38277, dtype: bool
0        False
1        False
2        False
3        False
4        False
         ...
38272    False
38273    False
38274    False
38275    False
38276    False
Name: maximum_minimum_nights_na, Length: 38277, dtype: bool
0        False
1        False
2        False
3        False
4        False
         ...
38272    False
38273    False
38274    False
38275    False
38276    False
Name: minimum_maximum_nights_na, Length: 38277, dtype: bool
0        False
1        False
2        False
3        False
4        False
         ...
38272    False
38273    False
38274    False
38275    False
38276    False
Name: maximum_maximum_nights_na, Length: 38277, dtype: bool
0        False
1        False
2        False
3        False
4        False
         ...
38272    False
38273    False
38274    False
38275    False
38276    False
Name: minimum_nights_avg_ntm_na, Length: 38277, dtype: bool
0        False
1        False
2        False
3        False
4        False
         ...
38272    False
38273    False
38274    False
38275    False
38276    False
Name: maximum_nights_avg_ntm_na, Length: 38277, dtype: bool
0        True
1        True
2        True
3        True
4        True
         ...
38272    True
38273    True
38274    True
38275    True
38276    True
Name: calendar_updated_na, Length: 38277, dtype: bool
0        False
1        False
2        False
3        False
4        False
         ...
38272     True
38273     True
38274     True
38275     True
38276     True
Name: review_scores_rating_na, Length: 38277, dtype: bool
0        False
1        False
2        False
3        False
4        False
         ...
38272     True
38273     True
38274     True
38275     True
38276     True
Name: review_scores_accuracy_na, Length: 38277, dtype: bool
0        False
1        False
2        False
3        False
4        False
         ...
38272     True
38273     True
38274     True
38275     True
38276     True
Name: review_scores_cleanliness_na, Length: 38277, dtype: bool
0        False
1        False
2        False
3        False
4        False
         ...
38272     True
38273     True
38274     True
38275     True
38276     True
Name: review_scores_checkin_na, Length: 38277, dtype: bool
0        False
1        False
2        False
3        False
4        False
         ...
38272     True
38273     True
38274     True
38275     True
38276     True
Name: review_scores_communication_na, Length: 38277, dtype: bool
0        False
1        False
2        False
3        False
4        False
         ...
38272     True
38273     True
38274     True
38275     True
38276     True
Name: review_scores_location_na, Length: 38277, dtype: bool
0        False
1        False
2        False
3        False
4        False
         ...
38272     True
38273     True
38274     True
38275     True
38276     True
Name: review_scores_value_na, Length: 38277, dtype: bool
0        False
1        False
2        False
3        False
4        False
         ...
38272     True
38273     True
38274     True
38275     True
38276     True
Name: reviews_per_month_na, Length: 38277, dtype: bool

Check that the DataFrame contains the new variables:

In [53]:
df.head()

,id,scrape_id,last_scraped,name,description,neighborhood_overview,host_id,host_name,host_since,host_location,...,maximum_nights_avg_ntm_na,calendar_updated_na,review_scores_rating_na,review_scores_accuracy_na,review_scores_cleanliness_na,review_scores_checkin_na,review_scores_communication_na,review_scores_location_na,review_scores_value_na,reviews_per_month_na
0,2595,20211204143024,2021-12-05,Skylit Midtown Castle,"Beautiful, spacious skylit studio in the heart...",Centrally located in the heart of Manhattan ju...,2845,Jennifer,2008-09-09,"New York, New York, United States",...,False,True,False,False,False,False,False,False,False,False
1,3831,20211204143024,2021-12-05,"Whole flr w/private bdrm, bath & kitchen(pls r...","Enjoy 500 s.f. top floor in 1899 brownstone, w...",Just the right mix of urban center and local n...,4869,LisaRoxanne,2008-12-07,"New York, New York, United States",...,False,True,False,False,False,False,False,False,False,False
2,5121,20211204143024,2021-12-05,BlissArtsSpace!,<b>The space</b><br />HELLO EVERYONE AND THANK...,NaN,7356,Garon,2009-02-03,"New York, New York, United States",...,False,True,False,False,False,False,False,False,False,False
3,5136,20211204143024,2021-12-05,"Spacious Brooklyn Duplex, Patio + Garden",We welcome you to stay in our lovely 2 br dupl...,NaN,7378,Rebecca,2009-02-03,"Brooklyn, New York, United States",...,False,True,False,False,False,False,False,False,False,False
4,5178,20211204143024,2021-12-05,Large Furnished Room Near B'way,Please don’t expect the luxury here just a bas...,"Theater district, many restaurants around here.",8967,Shunichi,2009-03-03,"New York, New York, United States",...,False,True,False,False,False,False,False,False,False,False

#### Replacing the missing values with mean values of the column

**Task**: For every column listed in `to_impute_selected`, fill the missing values with the corresponding mean of all values in the column (do not create new columns).

In [54]:
# YOUR CODE HERE
for x in to_impute[to_impute].index:
    df[x].fillna(df[x].mean(), inplace=True)

Check your results below. The code displays the count of missing values for each of the selected columns.

In [55]:
for colname in to_impute_selected:
    print("{} missing values count :{}".format(colname, np.sum(df[colname].isnull(), axis = 0)))

host_listings_count missing values count :0
host_total_listings_count missing values count :0
bathrooms missing values count :38277
bedrooms missing values count :0
beds missing values count :0

Why did the `bathrooms` column retain missing values after our imputation?

**Task**: List the unique values of the `bathrooms` column.

In [59]:
# YOUR CODE HERE
unique_bathrooms = df['bathrooms'].unique()
unique_bathrooms

array([nan])

The column did not contain a single value (except the `NaN` indicator) to begin with.

## Part 3. Perform One-Hot Encoding

Machine learning algorithms operate on numerical inputs. Therefore, we have to transform text data into some form of numerical representation to prepare our data for the model training phase. Some features that contain text data are categorical. Others are not. For example, we removed all of the features that contained URLs. These features were not categorical, but rather contained what is called unstructured text. However, not all features that contain unstructured text should be removed, as they can contain useful information for our machine learning problem. Unstructured text data is usually handled by Natural Language Processing (NLP) techniques. You will learn more about NLP later in this course. 

However, for features that contain categorical values, one-hot encoding is a common feature engineering technique that transforms them into binary representations.

We will first choose one feature column to one-hot encode: `host_response_time`. Let's inspect the unique values this feature can have.

In [60]:
df['host_response_time'].unique()

array(['within a day', 'a few days or more', 'within an hour', nan,
       'within a few hours'], dtype=object)

Note that each entry can contain one of five possible values. 

**Task**: Since one of these values is `NaN`, replace every entry in the column `host_response_time` that contains a `NaN` value with the string 'unavailable'.

In [63]:
# YOUR CODE HERE
# for entry in df['host_response_time']:
#     if entry == 'NaN':
#         entry = 'unavailable'

df['host_response_time'].fillna('unavailable', inplace=True)

Let's inspect the `host_response_time` column to see the new values.

In [64]:
df['host_response_time'].unique()

array(['within a day', 'a few days or more', 'within an hour',
       'unavailable', 'within a few hours'], dtype=object)

**Task**: Use `pd.get_dummies()` to one-hot encode the `host_response_time` column. Save the result to DataFrame `df_host_response_time`.

In [66]:
df_host_response_time = pd.get_dummies(df['host_response_time'])
df_host_response_time

,a few days or more,unavailable,within a day,within a few hours,within an hour
0,0,0,1,0,0
1,1,0,0,0,0
2,0,0,0,0,1
3,0,0,1,0,0
4,0,0,1,0,0
...,...,...,...,...,...
38272,0,0,0,1,0
38273,0,0,0,1,0
38274,0,0,0,0,1
38275,0,0,0,0,1
38276,0,0,0,0,1

**Task**: Since the `pd.get_dummies()` function returned a new DataFrame rather than making the changes to the original DataFrame `df`, add the new DataFrame `df_host_response_time` to DataFrame `df`, and delete the original `host_response_time` column from DataFrame `df`.

In [67]:
# YOUR CODE HERE
df= pd.concat([df,df_host_response_time],axis=1)
df.drop('host_response_time', axis=1,inplace=True)

Let's inspect DataFrame `df` to see the changes that have been made.

In [68]:
df.columns

Index(['id', 'scrape_id', 'last_scraped', 'name', 'description',
       'neighborhood_overview', 'host_id', 'host_name', 'host_since',
       'host_location', 'host_about', 'host_response_rate',
       'host_acceptance_rate', 'host_is_superhost', 'host_neighbourhood',
       'host_listings_count', 'host_total_listings_count',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'latitude', 'longitude',
       'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month',
       'label_price', 'host_listings_count_na', 'host_total_listings_count_na',
       'bathrooms_na', 'bedrooms_na', 'beds_na', 'minimum_minimum_nights_na',
       'maximum_minimum_nights_na', 'minimum_maximum_nights_na',
       'maximum_maximum_nights_na', 'minimum_nights_avg_ntm_na',
       'maximum_nights_avg_ntm_na', 'calendar_updated_na',
       'review_scores_rating_na', 'review_scores_accuracy_na',
       'review_scores_cleanliness_na', 'review_scores_checkin_na',
       'review_scores_communication_na', 'review_scores_location_na',
       'review_scores_value_na', 'reviews_per_month_na', 'a few days or more',
       'unavailable', 'within a day', 'within a few hours', 'within an hour'],
      dtype='object')

#### One-hot encode additional features

**Task**: Use the code cell below to find columns that contain string values  (the 'object' data type) and inspect the *number* of unique values each column has.

In [79]:
# YOUR CODE HERE
for x in df.columns:
    if df[x].dtype == 'object':
        print(df[x])
#         unique_vals = df[x].unique()
#         print(f"feature name '{x}' and value: {unique_vals}")

0        2021-12-05
1        2021-12-05
2        2021-12-05
3        2021-12-05
4        2021-12-05
            ...
38272    2021-12-05
38273    2021-12-05
38274    2021-12-05
38275    2021-12-05
38276    2021-12-05
Name: last_scraped, Length: 38277, dtype: object
0                                    Skylit Midtown Castle
1        Whole flr w/private bdrm, bath & kitchen(pls r...
2                                          BlissArtsSpace!
3                 Spacious Brooklyn Duplex, Patio + Garden
4                         Large Furnished Room Near B'way
                               ...
38272                  HUGE PRIVATE ROOM, AWESOME LOCATION
38273     LARGE PRVT ROOM, QUIET RESIDENCE PERFECTLOCATION
38274                        King Room - Midtown Manhattan
38275                             King Room - Bryant Park.
38276    ★Luxury in the ❤of Bklyn | Fast Wi-Fi | Sleeps...
Name: name, Length: 38277, dtype: object
0        Beautiful, spacious skylit studio in the heart...
1        Enjoy 500 s.f. top floor in 1899 brownstone, w...
2        <b>The space</b><br />HELLO EVERYONE AND THANK...
3        We welcome you to stay in our lovely 2 br dupl...
4        Please don’t expect the luxury here just a bas...
                               ...
38272    Must See! SPECTACULAR ONE FAMILY DUPLEX Home! ...
38273    Must See! SPECTACULAR ONE FAMILY DUPLEX Home! ...
38274    You can pack a lot into a minute in this centr...
38275                                                  NaN
38276    Stunning newly remodeled apartment in Bushwick...
Name: description, Length: 38277, dtype: object
0        Centrally located in the heart of Manhattan ju...
1        Just the right mix of urban center and local n...
2                                                      NaN
3                                                      NaN
4          Theater district, many restaurants around here.
                               ...
38272                                                  NaN
38273                                                  NaN
38274                                                  NaN
38275                                                  NaN
38276    Bushwick!<br /><br />This neighborhood is loca...
Name: neighborhood_overview, Length: 38277, dtype: object
0           Jennifer
1        LisaRoxanne
2              Garon
3            Rebecca
4           Shunichi
            ...
38272          Serin
38273          Serin
38274          Sinem
38275          Sinem
38276            Lee
Name: host_name, Length: 38277, dtype: object
0        2008-09-09
1        2008-12-07
2        2009-02-03
3        2009-02-03
4        2009-03-03
            ...
38272    2016-10-18
38273    2016-10-18
38274    2020-02-21
38275    2020-02-21
38276    2016-02-23
Name: host_since, Length: 38277, dtype: object
0                      New York, New York, United States
1                      New York, New York, United States
2                      New York, New York, United States
3                      Brooklyn, New York, United States
4                      New York, New York, United States
                              ...
38272                                                 US
38273                                                 US
38274                  New York, New York, United States
38275                  New York, New York, United States
38276    Washington, District of Columbia, United States
Name: host_location, Length: 38277, dtype: object
0        A New Yorker since 2000! My passion is creatin...
1        Laid-back Native New Yorker (formerly bi-coast...
2         I am an artist(painter, filmmaker) and curato...
3        Rebecca is an artist/designer, and Henoch is i...
4        I used to work for a financial industry but no...
                               ...
38272                                                  NaN
38273                                                  NaN
38274                                                  NaN
38275                                                  NaN
38276    Y|S- We provide travelers with an awesome expe...
Name: host_about, Length: 38277, dtype: object
0         80%
1          9%
2        100%
3        100%
4        100%
         ...
38272     97%
38273     97%
38274     94%
38275     94%
38276    100%
Name: host_response_rate, Length: 38277, dtype: object
0         17%
1         69%
2        100%
3         25%
4        100%
         ...
38272    100%
38273    100%
38274    100%
38275    100%
38276     97%
Name: host_acceptance_rate, Length: 38277, dtype: object
0        f
1        f
2        f
3        f
4        f
        ..
38272    f
38273    f
38274    f
38275    f
38276    f
Name: host_is_superhost, Length: 38277, dtype: object
0                   Midtown
1              Clinton Hill
2        Bedford-Stuyvesant
3         Greenwood Heights
4            Hell's Kitchen
                ...
38272              Elm Park
38273              Elm Park
38274                   NaN
38275                   NaN
38276                  NOMO
Name: host_neighbourhood, Length: 38277, dtype: object
0        ['email', 'phone', 'reviews', 'offline_governm...
1        ['email', 'phone', 'reviews', 'offline_governm...
2        ['email', 'phone', 'facebook', 'reviews', 'off...
3                            ['email', 'phone', 'reviews']
4                ['email', 'phone', 'facebook', 'reviews']
                               ...
38272                                   ['email', 'phone']
38273                                   ['email', 'phone']
38274                                            ['phone']
38275                                            ['phone']
38276    ['email', 'phone', 'google', 'reviews', 'jumio...
Name: host_verifications, Length: 38277, dtype: object
0        t
1        t
2        t
3        t
4        t
        ..
38272    t
38273    t
38274    t
38275    t
38276    t
Name: host_has_profile_pic, Length: 38277, dtype: object
0        t
1        t
2        t
3        t
4        f
        ..
38272    t
38273    t
38274    t
38275    t
38276    t
Name: host_identity_verified, Length: 38277, dtype: object
0                  New York, United States
1        Brooklyn, New York, United States
2                                      NaN
3                                      NaN
4                  New York, United States
                       ...
38272                                  NaN
38273                                  NaN
38274                                  NaN
38275                                  NaN
38276    Brooklyn, New York, United States
Name: neighbourhood, Length: 38277, dtype: object
0                   Midtown
1        Bedford-Stuyvesant
2        Bedford-Stuyvesant
3               Sunset Park
4                   Midtown
                ...
38272         Port Richmond
38273         Port Richmond
38274               Midtown
38275               Midtown
38276         Cypress Hills
Name: neighbourhood_cleansed, Length: 38277, dtype: object
0            Manhattan
1             Brooklyn
2             Brooklyn
3             Brooklyn
4            Manhattan
             ...
38272    Staten Island
38273    Staten Island
38274        Manhattan
38275        Manhattan
38276         Brooklyn
Name: neighbourhood_group_cleansed, Length: 38277, dtype: object
0                        Entire rental unit
1                        Entire guest suite
2               Private room in rental unit
3                        Entire rental unit
4               Private room in rental unit
                        ...
38272      Private room in residential home
38273      Private room in residential home
38274    Private room in serviced apartment
38275    Private room in serviced apartment
38276                    Entire rental unit
Name: property_type, Length: 38277, dtype: object
0        Entire home/apt
1        Entire home/apt
2           Private room
3        Entire home/apt
4           Private room
              ...
38272       Private room
38273       Private room
38274       Private room
38275       Private room
38276    Entire home/apt
Name: room_type, Length: 38277, dtype: object
0                1 bath
1                1 bath
2                   NaN
3             1.5 baths
4                1 bath
              ...
38272     1 shared bath
38273     1 shared bath
38274    1 private bath
38275               NaN
38276           4 baths
Name: bathrooms_text, Length: 38277, dtype: object
0        ["Extra pillows and blankets", "Baking sheet",...
1        ["Extra pillows and blankets", "Luggage dropof...
2        ["Kitchen", "Long term stays allowed", "Wifi",...
3        ["Kitchen", "BBQ grill", "Cable TV", "Carbon m...
4        ["Room-darkening shades", "Lock on bedroom doo...
                               ...
38272    ["Fire extinguisher", "Cooking basics", "Carbo...
38273    ["Fire extinguisher", "Cooking basics", "Carbo...
38274    ["Hangers", "Long term stays allowed", "Fire e...
38275    ["Hangers", "Long term stays allowed", "Fire e...
38276    ["Stainless steel electric stove", "Security c...
Name: amenities, Length: 38277, dtype: object
0        t
1        t
2        t
3        t
4        t
        ..
38272    t
38273    t
38274    t
38275    t
38276    t
Name: has_availability, Length: 38277, dtype: object
0        2021-12-05
1        2021-12-05
2        2021-12-05
3        2021-12-05
4        2021-12-05
            ...
38272    2021-12-05
38273    2021-12-05
38274    2021-12-05
38275    2021-12-05
38276    2021-12-05
Name: calendar_last_scraped, Length: 38277, dtype: object
0        2009-11-21
1        2015-01-05
2        2014-01-22
3        2014-01-02
4        2010-08-18
            ...
38272           NaN
38273           NaN
38274           NaN
38275           NaN
38276           NaN
Name: first_review, Length: 38277, dtype: object
0        2019-11-04
1        2021-10-22
2        2016-06-05
3        2021-08-08
4        2021-11-08
            ...
38272           NaN
38273           NaN
38274           NaN
38275           NaN
38276           NaN
Name: last_review, Length: 38277, dtype: object
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
38272    NaN
38273    NaN
38274    NaN
38275    NaN
38276    NaN
Name: license, Length: 38277, dtype: object
0        f
1        f
2        f
3        f
4        f
        ..
38272    f
38273    f
38274    t
38275    t
38276    t
Name: instant_bookable, Length: 38277, dtype: object

**Task**: Based on your findings, identify features that you think should be transformed using one-hot encoding.

1. Use the code cell below to inspect the unique *values* that each of these features have.

In [80]:
# YOUR CODE HERE
for x in df.columns:
    if df[x].dtype == 'object':
        unique_vals = df[x].unique()
        print(f"feature name '{x}' and value: {unique_vals}")

feature name 'last_scraped' and value: ['2021-12-05' '2021-12-04']
feature name 'name' and value: ['Skylit Midtown Castle'
 'Whole flr w/private bdrm, bath & kitchen(pls read)' 'BlissArtsSpace!'
 ... 'King Room - Midtown Manhattan' 'King Room - Bryant Park.'
 '★Luxury in the ❤of Bklyn | Fast Wi-Fi | Sleeps 14★']
feature name 'description' and value: ['Beautiful, spacious skylit studio in the heart of Midtown, Manhattan. <br /><br />STUNNING SKYLIT STUDIO / 1 BED + SINGLE / FULL BATH / FULL KITCHEN / FIREPLACE / CENTRALLY LOCATED / WiFi + APPLE TV / SHEETS + TOWELS<br /><br /><b>The space</b><br />- Spacious (500+ft²), immaculate and nicely furnished & designed studio.<br />- Tuck yourself into the ultra comfortable bed under the skylight. Fall in love with a myriad of bright lights in the city night sky. <br />- Single-sized bed/convertible floor mattress with luxury bedding (available upon request).<br />- Gorgeous pyramid skylight with amazing diffused natural light, stunning architectural details, soaring high vaulted ceilings, exposed brick, wood burning fireplace, floor seating area with natural zafu cushions, modern style mixed with eclectic art & antique treasures, large full bath, newly renovated kitchen, air conditioning/heat, high speed WiFi Internet, and Apple TV.<br />- Centrally located in the heart of Midtown Manhattan'
 'Enjoy 500 s.f. top floor in 1899 brownstone, w/ wood & ceramic flooring throughout, roomy bdrm, & upgraded kitchen & bathroom.\xa0 This space is unique but one of the few legal AirBnbs with a totally private bedroom, private full bathroom and private eat-in kitchen, SO PLEASE READ "THE SPACE" CAREFULLY.\xa0 It\'s sunny & loaded with everything you need! Your floor, and the common staircase/hallway/entryway are cleaned/sanitized per Airbnb\'s Enhanced Cleaning Protocol.<br /><br /><b>The space</b><br />We host on the entire top floor of our double-duplex brownstone in Clinton Hill on Gates near Classon Avenue - (7 blocks to C train, 5 blocks to G train, minutes to downtown Brooklyn & lower Manhattan).\xa0 It is not an apartment in the traditional sense, it is more of an efficiency set-up and is TOTALLY LEGAL with all short-term rental laws. The top floor for our guests consists of a sizable bedroom, full bath and eat-in kitchen for your exclusive use - you get the amenities of a private apartment '
 "<b>The space</b><br />HELLO EVERYONE AND THANKS FOR VISITING BLISS ART SPACE! <br /><br />Thank you all for your support. I've traveled a lot in the last year few years, to the  U.K. Germany, Italy and France! Loved Paris, Berlin and Calabria! Highly recommend all these places. <br /><br /><br />One room available for rent in a 2 bedroom apt in Bklyn. We share a common space with kitchen. I am an artist(painter, filmmaker) and curator who is working in the film industry while I'm building my art event production businesses.<br /><br />Price above is nightly for one person. Monthly rates available.  Price is $900 per month for one person. Utilities not included, they are about 50 bucks, payable when the bill arrives mid month.<br /> <br />Couples rates are slightly more for monthly and 90$ per night short term. If you are a couple please Iet me know and I’ll give you the monthly rate for that. Room rental is on a temporary basis, perfect from 2- 6 months - no long term requests please! "
 ...
 'Hi,<br /><br />Welcome to our house!!! The room is very large and spacious, can accommodate up to 4 people, fits 3 beds. Large walk-in closet and a private shower room. Private refrigerator also in your room!!<br /><br />Short walk (3-4minutes) to trains and buses. Easy to find free street parking spot. Laundromat is right across the street. <br /><br />Many local groceries stores near by. Many schools are located around the neighborhood, very safe and family friendly.'
 'You can pack a lot into a minute in this central location. The room feels more like a studio, with a private entrance from the hallway.  It’s spacious, giving the residents the most luxurious living experience without sharing any common spaces. It features a king size bed, ensuite bathroom, study desk, 60" smart TV with a streaming device, mini-fridge, microwave, coffee maker, and kettle. This room is a perfect fit for those looking for ultimate privacy, spacious bed, and comfort.'
 "Stunning newly remodeled apartment in Bushwick, steps from the J train (3 min walk) and a 20-minute commute to Manhattan. The apartment sleeps 12-14 and features 6 cozy bedrooms tastefully designed, luxury bathrooms with glass-enclosed walk-in showers, 75 inches 4K smart TV, blazing-fast wi-fi, and two full kitchens with all major appliances. Walking distance to highland park, walk, run, bike! No parties, gatherings, or get-togethers. No visitors beyond the confirmed guests.<br /><br />Stay here!<br /><br /><b>The space</b><br />Amenities:<br />•\tSmart lock access<br />•\tSecure high-speed wireless internet (400 Mbps) <br />•\t75” 4K smart TV with premium cable channels<br />•\tKeurig coffee maker<br />•\tMicrowave<br />•\tIron and ironing board <br />•\tHairdryer<br />•\tFresh towels, sheets, pillows<br />•\tOutdoor seating<br />•\tStay Here!<br /><br /><b>Guest access</b><br />Street parking. It's NYC so expect it to be busy!<br /><br /><b>Other things to note</b><br />Have fun!"]
feature name 'neighborhood_overview' and value: ['Centrally located in the heart of Manhattan just a few blocks from all subway connections in the very desirable Midtown location a few minutes walk to Times Square, the Theater District, Bryant Park and Herald Square.'
 'Just the right mix of urban center and local neighborhood; close to all but enough quiet for a calming walk. 15 to 45 minutes to most parts of Manhattan; 10 to 30 minutes to most Brooklyn points of interest; 45 minutes to 60 minutes to historic Coney Island.'
 nan ...
 'Groceries, delis, bakeries, cafes, restaurants, gourmet/vegan/vegetarian shops, souvenir, dollar stores, bars galore! Bushwick IS the new East Village! This is the place to be with everything you need within a 5 minute walk. CitiBike rentals 1 blk away, in 2 different directions. Main and express (work commute hours) trains 3 min walk from apt door... Myrtle/Bway JMZ trains.'
 'Soho , downtown, close to time square, ltaly town  Chinatown, Koreatown'
 'Spanish Harlem is one of the upcoming trendy neighbourhoods in manhattan. New bars and restaurants are opening all the time! With quick access to a downtown train and only minutes from central park its no wonder people from all over the city are relocating here!']
feature name 'host_name' and value: ['Jennifer' 'LisaRoxanne' 'Garon' ... 'Avigail' 'Bridgett' 'Maxinne']
feature name 'host_since' and value: ['2008-09-09' '2008-12-07' '2009-02-03' ... '2021-11-30' '2012-12-31'
 '2021-11-06']
feature name 'host_location' and value: ['New York, New York, United States' 'Brooklyn, New York, United States'
 'Berkeley, California, United States' ... 'Padua, Veneto, Italy'
 'Neffsville, Pennsylvania, United States'
 'Hartsdale, New York, United States']
feature name 'host_about' and value: ["A New Yorker since 2000! My passion is creating beautiful, unique spaces where unforgettable memories are made. It's my pleasure to host people from around the world and meet new faces. Welcome travelers! \r\n\r\nI am a Sound Therapy Practitioner and Kundalini Yoga & Meditation teacher. I work with energy and sound for relaxation and healing, using Symphonic gong, singing bowls, tuning forks, drums, voice and other instruments."
 'Laid-back Native New Yorker (formerly bi-coastal) and AirBnb host of over 6 years and over 400 stays!  Besides being a long-time and attentive AirBnb host, I am an actor, attorney, professor and group fitness instructor.'
 " I am an artist(painter, filmmaker) and curator who is working in the film industry while I'm building my business.\r\n\r\nI am extremely easy going and would like that you are the laid back\r\nand enjoy life kind of person. I also ask that you are open, honest\r\nand easy to communicate with as this is how I like to live my life.And of course creative people are very welcome!\r\n"
 ...
 "I am a responsible teacher living in the great city of New York! I love to travel and see the world and have traveled to Europe 5 times now and miss it when I'm not there. I love food, culture, great conversation, great wine, and great stories to bring home. I can't wait to get to South America someday soon, Greece and return to my favorite place... Italy. I look forward to staying at a great place such as yours and creating new and amazing memories!!!\r\n\r\nCheers! \r\n\r\nChris\r\n\r\nEat, laugh, live, play, breath, dream... love.\r\n\r\n"
 'Hello! We are Yan and Co! My wife Co is a wine expert from China and I am a musician originally from Puerto Rico. We have been married for about a year and have a spare room at a beautiful apartment with views of the Hudson River.  '
 'Y|S- We provide travelers with an awesome experience by providing top-notch accommodations in modern upscale homes across the US.\n']
feature name 'host_response_rate' and value: ['80%' '9%' '100%' nan '75%' '0%' '90%' '77%' '98%' '50%' '93%' '67%'
 '38%' '92%' '95%' '89%' '97%' '10%' '60%' '20%' '88%' '86%' '57%' '70%'
 '17%' '87%' '33%' '83%' '96%' '91%' '23%' '40%' '30%' '99%' '73%' '94%'
 '82%' '22%' '11%' '29%' '85%' '71%' '79%' '61%' '25%' '68%' '78%' '76%'
 '81%' '65%' '56%' '43%' '74%' '13%' '35%' '63%' '14%' '5%' '55%' '26%'
 '32%' '72%' '64%' '53%' '31%' '27%' '6%' '46%' '52%' '44%' '84%' '36%'
 '18%' '62%' '59%' '58%' '47%' '69%' '41%' '42%' '7%' '24%' '8%' '39%'
 '4%' '21%' '37%' '45%' '54%']
feature name 'host_acceptance_rate' and value: ['17%' '69%' '100%' '25%' nan '0%' '99%' '29%' '61%' '98%' '54%' '84%'
 '75%' '94%' '82%' '83%' '92%' '80%' '9%' '43%' '71%' '95%' '33%' '60%'
 '14%' '50%' '90%' '81%' '77%' '59%' '15%' '56%' '97%' '58%' '3%' '93%'
 '91%' '36%' '62%' '41%' '20%' '19%' '68%' '88%' '78%' '11%' '85%' '63%'
 '44%' '42%' '38%' '40%' '48%' '64%' '87%' '32%' '70%' '89%' '76%' '79%'
 '86%' '35%' '55%' '57%' '74%' '67%' '96%' '30%' '22%' '72%' '65%' '8%'
 '5%' '53%' '73%' '46%' '47%' '52%' '21%' '26%' '18%' '28%' '24%' '45%'
 '66%' '6%' '51%' '27%' '39%' '13%' '23%' '34%' '10%' '37%' '49%' '31%'
 '7%' '2%' '4%' '12%' '1%' '16%']
feature name 'host_is_superhost' and value: ['f' 't' nan]
feature name 'host_neighbourhood' and value: ['Midtown' 'Clinton Hill' 'Bedford-Stuyvesant' 'Greenwood Heights'
 "Hell's Kitchen" 'Upper West Side' 'Park Slope' 'Williamsburg'
 'East Harlem' 'Fort Greene' 'East Village' 'Harlem' 'Flatbush'
 'Alphabet City' 'Long Island City' 'Jamaica' 'Stuyvesant Heights'
 'East Williamsburg' 'Greenpoint' 'Soho' 'Chelsea' 'Upper East Side'
 'Prospect Heights' 'Washington Heights' 'Meatpacking District' 'Kips Bay'
 'Hamilton Heights' 'Bushwick' 'Carroll Gardens' 'West Village'
 'Lefferts Garden' 'Flatlands' 'Boerum Hill' 'Sunnyside' 'Lower East Side'
 'St. George' 'Tribeca' 'Highbridge' 'Ridgewood' nan 'Morningside Heights'
 'Ditmars Steinway' 'Ditmars / Steinway' 'Cobble Hill' 'Flatiron District'
 'Windsor Terrace' 'Chinatown' 'Greenwich Village' 'Midtown East'
 'Soundview' 'Crown Heights' 'Gowanus' 'Astoria' 'Kingsbridge Heights'
 'South Williamsburg' 'Brooklyn Heights' 'Downtown Brooklyn'
 'Forest Hills' 'Murray Hill' 'North Williamsburg' 'University Heights'
 'Gravesend' 'Baychester' 'East New York' 'Theatre District' 'Yorkville'
 'Sheepshead Bay' 'Bensonhurst' 'Rosebank' 'Richmond Hill' 'Gramercy Park'
 'Fordham' 'South Beach' 'Financial District' 'Brooklyn Navy Yard'
 'Times Square/Theatre District' 'Rego Park' 'Kensington' 'Little Italy'
 'Elmhurst' 'Stapleton' 'Flushing' 'Bay Ridge' 'Sunset Park' 'Maspeth'
 'Brighton Beach' 'Jackson Heights' 'Longwood' 'Inwood' 'Nolita'
 'Battery Park City' 'Bayside' 'Columbia Street Waterfront' 'Times Square'
 'New Springville' 'Red Hook' 'Cambridge' 'Civic Center' 'Grymes Hill'
 'Tottenville' 'Tompkinsville' 'Noho' 'DUMBO' 'Mariners Harbor' 'Woodside'
 'Concord' 'Melrose' 'College Point' 'Mount Eden' 'Union Square'
 'City Island' 'Pacific Beach' 'Canarsie' 'Port Morris' 'East Flatbush'
 'The Rockaways' 'Mott Haven' 'Ipanema' 'Midwood' 'Brownsville'
 'Southside' 'Williamsbridge' 'Woodhaven' 'Parkchester' 'Mid-Wilshire'
 'Bronxdale' 'South Street Seaport' 'Riverdale' 'Hudson Square'
 'Whitestone' 'Ozone Park' 'Corona' 'Manhattan' 'Bedford Park' 'Norwood'
 'Yehuda Hamaccabi' 'Concourse' 'Shoreditch' 'Zona Romántica'
 'Middle Village' 'Tremont' 'Topanga' 'Concourse Village' 'Wakefield'
 'Prospect Lefferts Gardens' 'Lighthouse HIll' 'East Bronx' 'Laguna Woods'
 'West Brighton' 'Utopia' 'South Ozone Park' 'Córcega' 'Kew Garden Hills'
 'Hillcrest' 'Santa Monica' 'The Bronx' 'Hollywood' 'Fresh Meadows'
 'Borough Park' 'Eastchester' 'Morris Park' 'Crotona' 'Woodstock'
 'Far Rockaway' 'East Elmhurst' 'Brooklyn' 'Manhattan Beach' 'Morrisania'
 'Marble Hill' 'Kingsbridge' 'Dongan Hills' 'Dumbo' 'Belmont'
 'Roosevelt Island' 'Castleton Corners' 'Hunts Point' 'Prenzlauer Berg'
 'South Side' 'Miami Beach' 'Howard Beach' 'Great Kills' 'Port Richmond'
 'Grasmere' 'Puerto Madero' 'Central Ward' 'Paddington' 'Belltown'
 'Morris Heights' 'Wicker Park' 'Shaw' 'New Brighton' 'Kailua/Kona'
 'Kauaʻi' 'Dalston' 'Spuyten Duyvil' 'Vinegar Hill'
 'Ludwigsvorstadt - Isarvorstadt' 'Bergen Beach' 'New Dorp' 'Downtown'
 'Coney Island' 'Clifton' 'Country Club' 'Castle Hill ' 'Zona 8'
 'Barrio Santa Lucía' 'Stapleton Heights' 'Sanlitun'
 'Southeast Washington' 'Bristol/Warner' 'Capitol View/Capitol View Manor'
 'Arlington Park' 'Bath Beach' 'San Giovanni' 'Central City' 'Glendale'
 'Midland Beach' 'Oakwood' 'Little Caribbean' 'Kilmainham' 'Pelham Bay'
 'Waikiki' 'Rockaway Beach' 'Annadale' 'Russian Hill'
 'South Hill/Rathnelly' 'Edenwald' 'Barrio Norte' 'Park Versailles'
 'Richmond' 'Josefov' 'Allerton' 'Todt Hill' 'Throgs Neck'
 'Meiers Corners' 'Marine Parade' 'South Lake Tahoe' 'II Arrondissement'
 'St Kilda East' 'Rittenhouse Square' 'Westchester Village' 'Claremont'
 'Westlake Hills' 'Merkaz HaIr' 'Dyker Heights' 'East Lake Terrace'
 'Upper Boggy Creek' 'University City' 'Mid-City' 'Stoke Newington'
 'North Bondi' 'College Park, MD' 'Condesa' 'East Downtown' 'Van Nest'
 'Friedrichshain' 'Greenridge' "Bull's Head" 'Collingwood/Fitzroy'
 'West Town/Noble Square' 'Châtelet - Les Halles - Beaubourg' 'Queens'
 'Hollywood South Central Beach' 'Randall Manor' 'Cypress Hills'
 'Entertainment District' 'Lev HaIr' 'Grant City' 'Dupont Circle'
 'Woollahra' 'Central Area' 'Dapuqiao' 'Peter Howell' 'Elm Park'
 'Rockaway Park' 'Arverne' 'Pelham Gardens' 'Pacific Heights' 'Montmartre'
 'Fort Wadsworth' 'New Dorp Beach' 'Le Port' 'Abbotsford' 'Park Cities'
 'Covent Garden' 'Retiro' 'Sunny Isles Beach' 'Bugis/Kampong Glam'
 'Silver Lake' 'Central LA' 'Ocean Hill' 'Beverly Hills' 'Palermo'
 'Venice' 'City of London' 'Garden Hills/Buckhead Village/Peachtree Park'
 'Browncroft' 'Arden Heights' 'South Richmond Hill' 'Homecrest'
 'North Corona' 'Camden Town' "Prince's Bay" 'South Lake Union'
 'Eltingville' 'Mid Island' 'Pyrmont' 'Columbia Heights' 'Bedford Pine'
 'Loop' 'Chicago Loop' 'Hackney' 'Setagaya District' 'Cerro Gordo'
 'Washington Square West' 'Westerleigh' 'Sunnyvale' 'Westwood' 'Arrochar'
 'Back Bay' 'Northstar Resort' 'West Bronx' 'Springfield Gardens'
 'Clason Point' 'Rossville' 'Graniteville' 'Copacabana' 'Bang Na'
 'Central West End' 'Notting Hill' 'Carlton' 'South First' 'Capitol Hill'
 'Lower Haight' 'West Farms' 'Irvine' 'Frunzensky' 'North Berkeley'
 'Northern Liberties' 'Lindenwood' 'Old Seminole Heights' 'Manchester'
 'Edgewood' 'Del Mar Heights' 'The Heights'
 'Lefferts Manor Historic District' 'Queens Village' 'Napili/Honokowai'
 'Recoleta' 'Laconia' 'São Paulo' 'Fordham Heights' 'Foxhurst' 'Ingleside'
 'Broadway Triangle' 'La Jolla' 'Dutch Kills' 'National Harbor'
 'Tzafon Yashan' 'Oakdale South' 'Marine Park' 'Fairview' 'Hollis'
 'Downtown Las Vegas' 'Shore Acres' 'Tulum Centro' 'Cambria Heights'
 'Cascade Green/Heritage Valley/Old Fairburn Village' 'Fieldston' 'Mantua'
 'West Side' 'Mill Basin' 'Smith Bay' 'Westside' 'Northwest Yonkers'
 'Brickell' 'Little Haiti' 'Mapleton' 'Spring Creek' 'South Slope'
 'Downtown Los Angeles' 'Getty Square' 'North Fork' 'Cherry Creek'
 'Bromley-by-Bow' 'North Philadelphia' 'Sugar House' 'The Bluffs'
 'Sandy Hill' 'Fordham Manor' 'Cannonborough Elliotborough'
 'Hamilton District' 'Fishtown' 'North Riverdale' 'Dietz'
 'Woodland Hills/Warner Center' 'Briarwood' 'French Quarter' 'Watertown'
 'Long Beach' 'Batignolles' 'Madison' 'Homestead' 'St. Albans'
 'Chapmantown' 'Downtown Jersey City' 'Central Business District'
 'Libertad' 'Springdale' 'Normandy Isles' 'Ormond Shores'
 'Pennington Bend' 'Hunter Hills' 'Pennsport' 'Central District'
 'Columbia Street Waterfront District' 'Lake Mohawk' 'Riverside'
 'Travis - Chelsea' 'Bridge Plaza' 'Coral Ridge' 'Shapira'
 'Jeffersonville' 'Laurel Canyon' 'Bel-Air' 'Downtown Austin' 'Table Rock'
 'Glen Park' 'Journal Square' 'Orange' 'Springfield/Belmont' 'West Ashley'
 'Marina Del Rey' 'La Concordia' 'Gerritsen Beach' 'Milwood' 'Park Hill'
 'Carroll Park' 'City of Marco' 'Central Oklahoma City' 'Canadensis'
 'Carnelian Bay' 'Townsite' 'South Scottsdale' 'New Cross' 'SoNo'
 'Laguna Beach On The Gulf Of Mexico' 'Rosedale' 'Ville-Marie' 'Woodrow'
 'Ormewood Park' '3G' 'Palms' 'Queen Village' 'Mid-Beach'
 'Westchester Square' 'Constable Hook' 'Seagate' 'Manchester Center'
 'Santa Cruz' 'Angel Park' 'Douglaston' 'Lakeville' 'Southeast Torrance'
 'Padre Island' 'Lenox Park' 'Fairmount' 'Fonatur' 'Claverack'
 'North Side' 'Old East Dallas' 'Buckhead' 'República' 'Kew Gardens'
 'Perimeter Center' 'Northridge' 'Southeast Yonkers' 'Westshore'
 'Palermo Hollywood' 'Newport' 'Queens Park' 'Kendall-Whittier'
 'Oliver Atlantic City' 'South Montebello' 'NOMO']
feature name 'host_verifications' and value: ["['email', 'phone', 'reviews', 'offline_government_id', 'kba', 'selfie', 'government_id', 'identity_manual', 'work_email']"
 "['email', 'phone', 'reviews', 'offline_government_id', 'kba', 'government_id']"
 "['email', 'phone', 'facebook', 'reviews', 'offline_government_id', 'selfie', 'government_id', 'identity_manual']"
 "['email', 'phone', 'reviews']"
 "['email', 'phone', 'facebook', 'reviews']"
 "['email', 'phone', 'facebook', 'google', 'reviews', 'jumio', 'government_id']"
 "['email', 'phone', 'facebook', 'reviews', 'jumio', 'offline_government_id', 'government_id']"
 "['email', 'phone', 'reviews', 'offline_government_id', 'selfie', 'government_id', 'identity_manual']"
 "['email', 'phone', 'reviews', 'offline_government_id', 'kba', 'selfie', 'government_id', 'work_email']"
 "['email', 'phone', 'reviews', 'jumio', 'government_id']"
 "['email', 'phone', 'reviews', 'kba', 'work_email']"
 "['email', 'phone', 'reviews', 'offline_government_id', 'kba', 'selfie', 'government_id', 'identity_manual']"
 "['email', 'phone', 'reviews', 'jumio', 'offline_government_id', 'government_id']"
 "['email', 'phone', 'reviews', 'kba']"
 "['email', 'phone', 'reviews', 'jumio', 'offline_government_id', 'selfie', 'government_id', 'identity_manual']"
 "['email', 'phone', 'reviews', 'offline_government_id', 'selfie', 'government_id']"
 "['phone']" "['email', 'phone', 'facebook', 'reviews', 'kba']"
 "['email', 'phone', 'reviews', 'offline_government_id', 'kba', 'government_id', 'work_email']"
 "['email', 'phone', 'facebook', 'reviews', 'jumio', 'offline_government_id', 'kba', 'selfie', 'government_id']"
 "['email', 'phone', 'reviews', 'offline_government_id', 'kba', 'selfie', 'government_id']"
 "['email', 'phone', 'facebook', 'reviews', 'jumio', 'offline_government_id', 'government_id', 'work_email']"
 "['email', 'phone', 'reviews', 'jumio', 'selfie', 'government_id', 'identity_manual']"
 "['email', 'phone', 'facebook', 'reviews', 'jumio', 'government_id']"

2.  List these features and explain why they would be suitable for one-hot encoding. Note your findings in the markdown cell below.

The features that are suitable for one hot encoding: neighbourhood, amenities, room_type, instant_bookable. The neighbourhood feature and amenities can be grouped into bigger subgroups so it can be used for one-hot encoding. The room_type feature can also be used in one-hot encoding because there are only 4 categories under the room_type feature so it can easily convert one-hot encoding.

<Double click this Markdown cell to make it editable, and record your findings here.>

**Task**: In the code cell below, one-hot encode one of the features you have identified and replace the original column in DataFrame `df` with the new one-hot encoded columns.

In [83]:
# YOUR CODE HERE
# room_type feature 
one_hot_encoded = pd.get_dummies(df['room_type'], prefix='room_type')
df.drop('room_type', axis=1, inplace=True)
df = pd.concat([df, one_hot_encoded], axis=1)

## Part 4. Explore Your Data

You will now perform exploratory data analysis in preparation for selecting your features as part of feature engineering. 

#### Identify Correlations

We will focus on identifying which features in the data have the highest correlation with the label.

Let's first run the `corr()` method on DataFrame `df` and save the result to the variable `corr_matrix`. Let's round the resulting correlations to five decimal places:

In [84]:
corr_matrix = round(df.corr(),5)
corr_matrix

,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,...,reviews_per_month_na,a few days or more,unavailable,within a day,within a few hours,within an hour,room_type_Entire home/apt,room_type_Hotel room,room_type_Private room,room_type_Shared room
id,1.00000,-0.0,0.58617,0.12986,0.12986,0.01000,0.08708,0.03540,NaN,0.04503,...,0.23064,0.01215,-0.35410,-0.01164,0.12780,0.29187,-0.04284,0.01698,0.03813,0.00958
scrape_id,-0.00000,1.0,0.00000,-0.00000,-0.00000,0.00000,-0.00000,0.00000,NaN,0.00000,...,-0.00000,0.00000,-0.00000,-0.00000,-0.00000,-0.00000,-0.00000,0.00000,0.00000,0.00000
host_id,0.58617,0.0,1.00000,0.03189,0.03189,0.04148,0.11620,0.02723,NaN,0.02202,...,0.12186,0.04055,-0.24094,-0.05562,0.01844,0.26491,-0.12862,0.07086,0.10957,0.03676
host_listings_count,0.12986,-0.0,0.03189,1.00000,1.00000,0.03475,-0.08843,-0.02621,NaN,-0.01710,...,0.19325,-0.03124,-0.11686,-0.03119,-0.01468,0.17132,0.01040,-0.00877,-0.00468,-0.01825
host_total_listings_count,0.12986,-0.0,0.03189,1.00000,1.00000,0.03475,-0.08843,-0.02621,NaN,-0.01710,...,0.19325,-0.03124,-0.11686,-0.03119,-0.01468,0.17132,0.01040,-0.00877,-0.00468,-0.01825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
within an hour,0.29187,-0.0,0.26491,0.17132,0.17132,-0.02598,0.08358,0.11060,NaN,0.06432,...,-0.11376,-0.13339,-0.57898,-0.18761,-0.25777,1.00000,0.01693,0.04812,-0.01967,-0.01831
room_type_Entire home/apt,-0.04284,-0.0,-0.12862,0.01040,0.01040,-0.02656,-0.14909,0.45742,NaN,0.35604,...,-0.07266,-0.00872,-0.04946,0.06668,0.00195,0.01693,1.00000,-0.07933,-0.95966,-0.13155
room_type_Hotel room,0.01698,0.0,0.07086,-0.00877,-0.00877,0.02825,-0.04860,-0.01671,NaN,-0.02448,...,-0.00339,-0.01191,-0.03010,0.00451,-0.01658,0.04812,-0.07933,1.00000,-0.06674,-0.00915
room_type_Private room,0.03813,0.0,0.10957,-0.00468,-0.00468,0.01830,0.15128,-0.44105,NaN,-0.33917,...,0.06905,0.00571,0.05008,-0.06601,0.00196,-0.01967,-0.95966,-0.06674,1.00000,-0.11067
room_type_Shared room,0.00958,0.0,0.03676,-0.01825,-0.01825,0.01707,0.02280,-0.06358,NaN,-0.05944,...,0.01793,0.01973,0.01648,-0.00648,-0.00597,-0.01831,-0.13155,-0.00915,-0.11067,1.00000

The result is a computed *correlation matrix*. The values on the diagonal are all equal to 1 because they represent the correlations between each column with itself. The matrix is symmetrical with respect to the diagonal.<br>

We only need to observe correlations of all features with the column `label_price` (as opposed to every possible pairwise correlation). Se let's query the `label_price` column of this matrix:

**Task**: Extract the `label_price` column of the correlation matrix and save the results to the variable `corrs`.

In [86]:
# YOUR CODE HERE
corrs = corr_matrix['label_price']
corrs

id                           0.07907
scrape_id                   -0.00000
host_id                      0.04053
host_listings_count          0.13104
host_total_listings_count    0.13104
                              ...
within an hour               0.11721
room_type_Entire home/apt    0.33529
room_type_Hotel room         0.10587
room_type_Private room      -0.34108
room_type_Shared room       -0.04563
Name: label_price, Length: 70, dtype: float64

**Task**: Sort the values of the series we just obtained in the descending order and save the results to the variable `corrs_sorted`.

In [90]:
corrs_sorted = corrs.sort_values(ascending=False)
corrs_sorted

label_price               1.00000
price                     0.71112
accommodates              0.50062
bedrooms                  0.41996
beds                      0.37370
                           ...
room_type_Private room   -0.34108
bathrooms                     NaN
calendar_updated              NaN
bathrooms_na                  NaN
calendar_updated_na           NaN
Name: label_price, Length: 70, dtype: float64

**Task**: Use Pandas indexing to extract the column names for the top two correlation values and save the results to the Python list `top_two_corr`. Add the feature names to the list in the order in which they appear in the output above. <br> 

<b>Note</b>: Do not count the correlation of `label` column with itself, nor the `price` column -- which is the `label` column prior to outlier removal.

In [93]:
top_two_corr = corrs_sorted[1:3].index.tolist()
top_two_corr

['price', 'accommodates']

#### Bivariate Plotting: Produce Plots for the Label and Its Top Correlates

Let us visualize our data.

We will use the `pairplot()` function in `seaborn` to plot the relationships between the two features and the label.

**Task**: Create a DataFrame `df_corrs` that contains only three columns from DataFrame `df`: the label, and the two columns which correlate with it the most.

In [97]:
df_corrs = corrs_sorted[0:3].index.tolist()
df_corrs

['label_price', 'price', 'accommodates']

**Task**: Create a `seaborn` pairplot of the data subset you just created. Specify the *kernel density estimator* as the kind of the plot, and make sure that you don't plot redundant plots.

<i>Note</i>: It will take a few minutes to run and produce a plot.

In [ ]:
# YOUR CODE HERE
import seaborn as sns
df_subset = df[top_two_corr]
sns.pairplot(df_subset, kind='kde', diag_kind='kde')
plt.show()

## Part 5: Analysis

1. Think about the possible interpretation of the plot. Recall that the label is the listing price. <br> How would you explain the relationship between the label and the two features? Is there a slight tilt to the points cluster, as the price goes up?<br>
2. Are the top two correlated features strongly or weakly correlated with the label? Are they features that should be used for our predictive machine learning problem?
3. Inspect your data matrix. It has a few features that contain unstructured text, meaning text data that is neither numerical nor categorical. List some features that contain unstructured text that you think are valuable for our predictive machine learning problem. Are there other remaining features that you think need to be prepared for the modeling phase? Do you have any suggestions on how to prepare these features?

Record your findings in the cell below.

<Double click this Markdown cell to make it editable, and record your findings here.>